trigger:
- azure-pipelines

pool: my-agent-pool

steps:
- checkout: self
- script: |
    npm install
    npm run build
    mv dist www
    for file in www/*; do
      curl --ftp-create-dirs -T $file -u $FTP_USERNAME:$env:FTP_PASSWORD ftp://$FTP_SERVER:21/www/$(basename $file)
    done
  displayName: 'Upload Directory via FTP on macOS'
  env:
    FTP_SERVER: $(FTP_HOST)
    FTP_USERNAME: $(FTP_USER)
    FTP_PASSWORD: $(FTP_PWD)