trigger:
- main

pool: my-agent-pool

steps:
- checkout: self

- script: |
    npm install
    npm run build
    mv dist www
  displayName: 'npm install & build www folder'

- bash: |
    FILES=$(curl -u $FTP_USERNAME:$FTP_PASSWORD $FTP_SERVER/www/assets/)
    for line in $FILES; do
      ftp -inv $FTP_SERVER <<EOF
      user FTP_USERNAME FTP_PASSWORD
      delete www/assets/$line
      bye
      EOF
      done
  displayName: 'Delete preview .css & .js file'
  env:
    FTP_SERVER: $(FTP_HOST2)
    FTP_USERNAME: $(FTP_USER)
    FTP_PASSWORD: $(FTP_PWD)

- bash: |
    for file in www/*; do 
      if [[ -d $file ]]; then 
        for subfile in $file/*; do 
          curl -T $subfile -u $FTP_USERNAME:$FTP_PASSWORD $FTP_SERVER/www/assets/;
          done; 
      else 
        curl -T $file -u $FTP_USERNAME:$FTP_PASSWORD $FTP_SERVER/www/;
      fi;
    done 
  displayName: 'Upload Directory via FTP on macOS'
  env:
    FTP_SERVER: $(FTP_HOST)
    FTP_USERNAME: $(FTP_USER)
    FTP_PASSWORD: $(FTP_PWD)