trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: |
      npm install
      npm run build
    displayName: "npm install & build www folder"

  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: 'ftp.cluster029.hosting.ovh.net'
      username: 'romeofu'
      password: '180403Romeo'
      implicitFTPS: true
      rootDirectory: 'www'
      filePatterns: '**'
      remoteDirectory: '/upload/$(Build.BuildId)/'
      clean: false
      cleanContents: false
      preservePaths: false
      trustSSL: false