trigger:
- main

pool: my-agent-pool

steps:
- checkout: self
- script: |
    for file in build/*; do
      curl --ftp-create-dirs -T $file -u $FTP_USERNAME:$FTP_PASSWORD ftp://$FTP_SERVER/path/to/remote/directory/$(basename $file)
    done
  displayName: 'Upload Directory via FTP on macOS'
  env:
    FTP_SERVER: $(FTP_SERVER)
    FTP_USERNAME: $(FTP_USERNAME)
    FTP_PASSWORD: $(FTP_PASSWORD)