trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- script: |
    apt-get update && apt-get install -y ftp
    FTP_SCRIPT="open $FTP_SERVER
    user $FTP_USERNAME $FTP_PASSWORD
    binary
    mput www/*
    bye"
    echo "$FTP_SCRIPT" | ftp -inv
  displayName: 'Upload Directory via FTP'
  env:
    FTP_SERVER: $(FTP_SERVER)
    FTP_USERNAME: $(FTP_USERNAME)
    FTP_PASSWORD: $(FTP_PASSWORD)